### ISSUE TITLE
Reanimated warning

### ISSUE THREAD

**Issue by mrevanzak** [saulamsal/react-native-sheet-transitions#1]
[Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.

If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.

I’ll help fix it if I can find the culprit.

**Comment by tomekzaw** [comment]
Seems like this warning is triggered by this read in dependency array, you might want to replace `scrollState.value` with simply `scrollState`:
https://github.com/saulamsal/react-native-sheet-transitions/blob/7117a1996ea827f01f0b80b4f2765945e7544b1a/src/SheetScreen.tsx#L133

**Comment by mrevanzak** [comment]
> Seems like this warning is triggered by this read in dependency array, you might want to replace `scrollState.value` with simply `scrollState`:
> 
> https://github.com/saulamsal/react-native-sheet-transitions/blob/7117a1996ea827f01f0b80b4f2765945e7544b1a/src/SheetScreen.tsx#L133

good finds! i think you are correct
